=== co-cddo/data-catalogue-metadata/schema/data_marketplace_resource_group_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Data Marketplace Metadata - Resource Group",
  "$id": "Schemas/ResourceGroup",
  "description": "Data Marketplace Metadata schema for a Resource Group",
  "type": "object",
  "properties": {
    "@type": {
      "description": "Should be a DCAT object type",
      "enum": ["ResourceGroup"]
    },
    "accessRights": {
      "description": "A rights statement that concerns how the distribution is accessed.",
      "enum": [
        "INTERNAL",
        "OPEN",
        "COMMERCIAL"
      ]
    },
    "alternativeTitle": {
      "description": "An alternative name used as a substitute or additional access point for an information resource.",
      "type": "array",
      "items": {
       "type": "string",
      "maxLength": 200
      }
    },
    "contactPoint": {
      "description": "Contact information",
      "type": "object",
      "properties": {
        "contactName": {
          "type": "string",
          "maxLength": 50
        },
        "email": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9_.+\\-]+@[a-zA-Z0-9\\-]+\\.[a-zA-Z0-9\\-.]+$"
        }
      },
      "required": [
        "contactName",
        "email"
      ]
    },
    "created": {
      "description": "The date on which the data was created.",
      "$ref": "#/schemas/YYYY-MM-DD"
    },
    "creator": {
      "description": "The business entity responsible for creating or compiling the original content of an information resource..",
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 75
      }
    },
    "description": {
      "description": "A concise narrative of the content of an information resource. A free-text account of the distribution.",
      "type": "string",
      "maxLength": 4096
    },
    "distribution": {
      "type": "array",
      "items": {
        "$ref": "#/schemas/distribution"
      }
    },
    "identifier": {
      "description": "A unique number, code, or reference value assigned to an information resource within a given context.",
      "type": "string",
      "maxLength": 50
    },
    "issued": {
      "description": "The date the data was issued.",
      "$ref": "#/schemas/YYYY-MM-DD"
    },
    "keyword": {
      "description": "Uncontrolled terms (words or phrases) assigned to describe an information resource.",
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 75
      }
    },
    "licence": {
      "description": "Reference to the legal document outlining access and usage rights for an information resource.",
      "type": "string",
      "maxLength": 250
    },
    "member": {
      "description": "List of the Resources within the group defined by this object. It can contain an array of datasets, data services or references to those resources",
      "type": "array",
      "items": {
        "anyOf": [
          { "$ref": "./../schema/data_marketplace_dataset_schema.json" },
          { "$ref": "./../schema/data_marketplace_data_service_schema.json" },
          { "type": "string", "maxLength": 250 }
        ]
      }
    },
    "modified": {
      "description": "The date on which the data changed.",
      "$ref": "#/schemas/YYYY-MM-DD"
    },
    "publisher": {
      "description": "The business entity responsible for making an information resource publicly available.",
      "type": "string",
      "maxLength": 75
    },
    "relatedResource": {
      "description": "A resource that bears a close relationship to the described resource.",
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 250
      }
    },
    "securityClassification": {
      "description": "An information security designation that identifies the minimum level of protection assigned to an information resource.",
      "enum": [
        "OFFICIAL",
        "SECRET",
        "TOP_SECRET",
        "NOT_APPLICABLE"
      ]
    },
    "summary": {
      "description": "A short textual summary of the resource with a maximum length of 250 characters.",
      "type": "string",
      "maxLength": 250
    },
    "supplierIdentifier": {
      "supplierIdentifier": "The indentifier providered by the metadata supplier. The indentifier used to identify the resource group in their systems.",
      "type": "string",
      "maxLength": 50
    },
    "theme": {
      "description": "Topic: A controlled term that expresses the broad topical content of an information resource. Subject: A controlled term that expresses a topic of the intellectual content of an information resource.",
      "type": "array",
      "items": {
        "enum": [
          "Agriculture, fisheries and forestry",
          "Business, economics and finance",
          "Crime and justice",
          "Culture, leisure and sport",
          "Education",
          "Energy",
          "Environment and nature",
          "Geography",
          "Government and public sector",
          "Health and care",
          "Population and society",
          "Science and technology",
          "Transport and infrastructure"
        ]
      }
    },
    "title": {
      "description": "The full and formal name given to an information resource. A name given to the distribution.",
      "type": "string",
      "maxLength": 200
    },
    "updateFrequency": {
      "description": "",
      "enum": [
        "freq:triennial",
        "freq:biennial",
        "freq:annual",
        "freq:semiannual",
        "freq:threeTimesAYear",
        "freq:quarterly",
        "freq:bimonthly",
        "freq:monthly",
        "freq:semimonthly",
        "freq:biweekly",
        "freq:threeTimesAMonth",
        "freq:weekly",
        "freq:semiweekly",
        "freq:threeTimesAWeek",
        "freq:daily",
        "freq:continuous",
        "freq:irregular"
      ]
    },
    "version": {
      "description": "An incremental identifier used to track which version of the object is being used.",
      "type": "string",
      "maxLength": 15
    }
  },
  "required": [
    "contactPoint",
    "description",
    "identifier",
    "keyword",
    "member",
    "publisher",
    "securityClassification",
    "theme",
    "title"
  ],
  "schemas": {
    "distribution": {
      "$id": "schemas/distribution",
      "description": "A specific representation of a resource group.",
      "type": "object",
      "properties": {
        "accessService": {
          "description": "A data service that gives access to the distribution of the resource group. This should be reference to a DataService.",
          "type": "string",
          "maxLength": 250
        },
        "byteSize": {
          "description": "The size of the distribution in bytes.",
          "type": "integer",
          "format": "int64"
        },
        "identifier": {
          "description": "A unique number, code, or reference value assigned to an information resource within a given context.",
          "type": "string",
          "maxLength": 75
        },
        "issued": {
          "description": "The date on which a distribution was originally published",
          "$ref": "#/schemas/YYYY-MM-DD"
        },
        "licence": {
          "description": "A legal document under which the distribution is made available.",
          "type": "string",
          "maxLength": 100
        },
        "mediaType": {
          "description": "The IANA media type, or file format, type, or extention, of the distribution file.",
          "type": "string",
          "maxLength": 50
        },
        "modified": {
          "description": "The date on which the distribution is changed.",
          "$ref": "#/schemas/YYYY-MM-DD"
        },
        "title": {
          "description": "A name given to the distribution.",
          "type": "string",
          "maxLength": 250
        }
      }
    },
    "YYYY-MM-DD": {
      "description": "Date in format YYYY-MM-DD.",
      "type": "string",
      "pattern": "20\\d{2}\\-[0-1]\\d\\-[0-3]\\d"
    }
  },
  "additionalProperties": false
}

=== co-cddo/data-catalogue-metadata/samples/group_of_dataset_references.json
{
  "title": "A group containing references to datasets",
  "alternativeTitle": [
    "Dataset reference group"
  ],
  "description": "An example of the object that will allow datasets to be grouped. The datasets are identified an reference id. This is a sub-type of Dataset",
  "keyword": [
  ],
  "theme": [
  ],
  "contactPoint": {
    "contactName": "Rob Nichols",
    "email": "robert.nichols@digital.cabinet-office.gov.uk"
  },
  "creator": [
    "central-digital-and-data-office"
  ],
  "publisher": "academy-for-social-justice",
  "securityClassification": "OFFICIAL",
  "identifier": "8d085327-21b6-4d8b-9705-88faad231d99",
  "relatedResource": [
    ""
  ],
  "member": [
    "8d085327-21b6-4d8b-9705-88faad231d22",
    "8d085327-21b6-4d8b-9705-88faad231d62",
    "8d085327-21b6-4d8b-9705-88faad231d63"
  ]
}

=== co-cddo/data-catalogue-metadata/samples/group_of_datasets.json
{
  "title": "A group containing a dataset",
  "alternativeTitle": [
    "Dataset group"
  ],
  "description": "An example of the object that will allow datasets to be grouped. This is a sub-type of Dataset",
  "keyword": [
  ],
  "theme": [
  ],
  "contactPoint": {
    "contactName": "Rob Nichols",
    "email": "robert.nichols@digital.cabinet-office.gov.uk"
  },
  "creator": [
    "central-digital-and-data-office"
  ],
  "publisher": "academy-for-social-justice",
  "securityClassification": "OFFICIAL",
  "identifier": "8d085327-21b6-4d8b-9705-88faad231d99",
  "relatedResource": [
    ""
  ],
  "member": [
    {
      "title": "Advance Passenger Information (API) ",
      "alternativeTitle": [
        "Travel Data"
      ],
      "summary": "Airline passenger travel data",
      "description": "Travel data and personal data given to airlines by passenger. API covers  both inbound and outbound air passengers. API includes the passengerâ€™s full name, nationality, date of birth, gender and travel document number, type and country of issue.The data does not include those arriving by sea or rail routes, by private aircraft or via the Common Travel Area (CTA).",
      "keyword": [
        "Air travel",
        "Passport",
        "Airports",
        "leaving UK",
        "entering UK"

      ],
      "theme": [
        "Transport and infrastructure",
        "Population and society"
      ],
      "contactPoint": {
        "contactName": "Rob Nichols",
        "email": "robert.nichols@digital.cabinet-office.gov.uk"
      },
      "creator": [
        "central-digital-and-data-office"
      ],
      "publisher": "academy-for-social-justice",
      "securityClassification": "OFFICIAL",
      "identifier": "8d085327-21b6-4d8b-9705-88faad231d62",
      "relatedResource": [
        ""
      ]
    }
  ]
}
